export {default as Main } from './Main'
export {default as Navbar } from './Navbar/Navbar'
export {default as Home } from './Home/Home'
export {default as About } from './About/About'
export {default as Contact } from './Contact/Contact'
export {default as Resume } from './Resume/Resume'
export {default as Portfolio } from './Portfolio/Portfolio'
